hparams:
  batch_size: 16
  learning_rate: 1e-4
  fusion_method: 'concate'
  cxr_model: 'resnet50'
  hidden_size: 256
  ehr_n_head: 4
  ehr_n_layers: 1
  ehr_dropout: 0.2
  lr: 0.0001
  matched: True
  rho: 0.5
  weight_decay: 0.6
  score_weight: 0.5
  momentum: 0.9
  model_name: 'masam'
  gpu: 0
  save_trace: False
  save_eigenvalue: False
  sam_decomp: True
  uniloss: True
  sam: False
  sagm: False
  save_trace_epoch: False
  save_eigenvalue_epoch: False
  save: False
  draw_sam_iamge: False
  dynamic_mode: True
  loss_multi: 1.0
  loss_ehr: 1.0
  loss_cxr: 1.0
  task: 'mortality'
  seed: 42
